const String baseURL= 'https://kre8consultancy.com/api/'; //'https://kre8consultancy.com/api/';
const String loginURL='login';
const String logOutURL='logout';
const String getProfileURL='getProfile';
const String userRegister='userRegister';
const String updateProfile='updateProfile';
const String getAges='get-ages';
const String getChronicDisease='get-chronic-disease';
const String getComplaintStatus='get-complaint-status';
const String getDangerousActivities='get-dangerous-activities';
const String getEngineCapacity='get-engine-capacity';
const String getEngineType='get-engine-type';
const String getInsurancePeriod='get-insurance-period';
const String getInsurancePeriodYears='get-life-insurance-period';
const String getMedicalNetwork='get-medical-network';
const String getMotorPlan='get-motor-plan';
const String getProtectionSystem='get-protection-system';
const String getInPatientDeductible='get-in-patient-deductible';
const String getOutPatientDeductible='get-out-patient-deductible';
const String getNumberOfVisit='get-number-of-visits';
const String getClaimDeductible='get-claim-deductible';
const String getNationality='get-nationality';
const String getCurrency='get-currency';
const String getGeographicalArea='get-geographical-area';
const String getVehicleBrand='get-vehicle-brands';
const String getVehicleColor='get-vehicle-color';
const String getVehicleType='get-vehicle-type';
const String getCity='get-city';
const String getDistrict='get-district';
const String getCountry='get-country';
const String getOccupation="get-occupations";
const String addMotorInsurance='add-motor-insurance';
const String addHomeInsurance='add-home-insurance';
const String addLifeInsurance='add-life-insurance';
const String addPersonalAccidentInsurance='add-personal-accident-insurance';
const String getPersonalAccidentInsurance='getPersonalAccidentPlanInsurancePlan';
const String addCriticalIllnessInsurance='add-critical-illness-insurance';
const String getCriticalIllnessInsurancePlan='getCriticalIllnessInsurancePlan?limit=';
const String getPersonalAccidentPlanInsurancePlan='getPersonalAccidentPlanInsurancePlan?limit=';
const String getLifeInsurancePlan='getLifeInsurancePlan';
const String insuranceLimitUrl='insuranceLimit?insurance_type=';
const String getHomeInsurancePlan='getHomeInsurancePlan?limit=';
const String getDentalInsurancePlan='getDentalInsurancePlan?limit=';
const String addDentalInsurance='add-dental-insurance';
const String getPetsInsurancePlan='getPetsInsurancePlan?limit=';
const String addPetsInsurance='add-pets-insurance';
const String getOfficeInsurancePlan='getOfficeInsurancePlan?limit=';
const String addOfficeInsurance='add-office-insurance';
const String getTravelInsurancePlan='getTravelInsurancePlan';
const String addTravelInsurance='add-travel-insurance';
const String getComprehensivePlan='getComprehensivePlan';
const String getCompulsory3MonthsPlan='getCompulsory3MonthsPlan';
const String getCompulsory6MonthsPlan='getCompulsory6MonthsPlan';
const String getCompulsory9MonthsPlan='getCompulsory9MonthsPlan';
const String getCompulsory12MonthsPlan='getCompulsory12MonthsPlan';
const String getTotalLossPlan='getTotalLossPlan';
const String getMarineInsurancePlan ='getMarineInsurancePlan?limit=';
const String addMarineInsurance ='add-marine-insurance';
const String getVehicleCategory ='get-vehicle-category?brand_id=';
const String getInPatientInsurancePlan ='getInPatientInsurancePlan';
const String getOutPatientInsurancePlan ='getOutPatientInsurancePlan';
const String addIndividualMedicalInsurance ='add-individual-medical-insurance';
const String addFamilyMedicalInsurance ='add-family-medical-insurance';
const String getPolicyDetails ='getPolicyDetails';
const String getClaimsList ='claims-list';
const String addClaims ='add-claims';
const String addComplaint ='add-complaint';
const String getInsuranceType ='get-insurance-type';
const String getInsuranceCompany ='get-insurance-company?insurance_type_id=';
const String getComplaintList ='get-complaint-list';
const String addStoreTransaction ='store-transaction';
const String editClaims ='edit-claims';
const String sendClaimsMessage ='send-claims-message';
const String claimsChatsList ='claims-chats-list?claim_id=';
const String contactChatsList ='contact-chats-list';
const String sendContactMessage ='send-contact-message';
const String getSocialMedia ='get-social-media';
const String getItemCategory ='get-item-category';
const String getItemSubcategory ='get-item-subcategory?id=';
const String getTypeCover ='get-type-cover';
const String uploadDocument ='upload-document';
const String removeUploadDocument ='remove-upload-document?document=';
const String insuranceCurrent ='insuranceCurrent?insurance_type=';
const String forgotOtpSend ='forgot-otp-send';
const String registerOtpSend ='register-otp-send';
const String forgotPassword ='forgot-password';
const String getDiscountAmount ='get-discount-amount';
const String getDiscountCoupons ='get-discount-coupons';
const String getBannerURL ='get-banner';
const String getPetBreeds = 'pet-breeds/';
const String chatStartURL = 'chat/start';
const String chatSendURL = 'chat/send';
const String chatListURL = 'chat/list';
String getChatMessagesURL(int chatId, {int page = 1}) => 'chat/$chatId/messages?page=$page';
String markChatReadURL(int chatId) => 'chat/$chatId/mark-read';
const String saveSignatureUrl = 'save-signature';
const String generateFinalPdf = 'generate-final-pdf';
const String getTermsAndConditions = 'terms-and-conditions?id=';



